In [26]:
import pandas as pd
from io import StringIO

In [27]:
df = pd.read_csv("/home/rendika/Documents/data/export-user-hotspot-mikhmon-2024-06-04.csv")
df.head(10)

,Username,Password,Profile,Time Limit,Data Limit,Comment
0,default-trial,NaN,NaN,NaN,NaN,counters and limits for trial users
1,admin,admin,default,NaN,NaN,NaN
2,taFBL,taFBL,HARIAN,1d,NaN,vc-773-06.01.24-testing
3,tayHw,tayHw,HARIAN,1d,NaN,vc-773-06.01.24-testing
4,taUDL,taUDL,HARIAN,1d,NaN,vc-773-06.01.24-testing
5,taLWw,taLWw,HARIAN,1d,NaN,vc-773-06.01.24-testing
6,taE2U,taE2U,HARIAN,1d,NaN,vc-773-06.01.24-testing
7,taHRH,taHRH,HARIAN,1d,NaN,vc-773-06.01.24-testing
8,taxU3,taxU3,HARIAN,1d,NaN,vc-773-06.01.24-testing
9,taprJ,taprJ,HARIAN,1d,NaN,vc-773-06.01.24-testing

In [28]:
import numpy as np
import random
from datetime import time, timedelta

# Function to generate a random time within a specified range
def generate_random_time(start, end):
    start_seconds = start.hour * 3600 + start.minute * 60 + start.second
    end_seconds = end.hour * 3600 + end.minute * 60 + end.second
    random_seconds = random.randint(start_seconds, end_seconds)
    return str(timedelta(seconds=random_seconds))

# Remove the specified columns
df.drop(columns=['Password', 'Comment', 'Data Limit'], inplace=True)

# Generate "uptime" data based on profile
uptimes = []
for profile in df['Profile']:
    if profile == ' KERJA':
        # Generate time between 10:00:00 and 17:00:00
        uptimes.append(generate_random_time(time(10, 0, 0), time(17, 0, 0)))
    else:
        # Generate time between 20:00:00 and 23:00:00
        uptimes.append(generate_random_time(time(20, 0, 0), time(23, 0, 0)))

# Add the "uptime" column to the DataFrame
df['uptime'] = uptimes

# Display the modified DataFrame
df.head()

        Username  Profile Time Limit    uptime
0  default-trial      NaN        NaN  22:13:14
1          admin  default        NaN  22:23:45
2          taFBL   HARIAN         1d  20:22:09
3          tayHw   HARIAN         1d  21:23:28
4          taUDL   HARIAN         1d  22:35:29

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Username    506 non-null    object
 1   Profile     505 non-null    object
 2   Time Limit  29 non-null     object
 3   uptime      506 non-null    object
dtypes: object(4)
memory usage: 15.9+ KB

In [30]:
df.to_csv("fixedmock.csv", index=False)

In [32]:
# !pip install ace_tools

ERROR: Could not find a version that satisfies the requirement ace_tools (from versions: none)
ERROR: No matching distribution found for ace_tools

In [ ]:
import pandas as pd
import numpy as np

# Load the provided CSV file
file_path = '/mnt/data/fixedmock.csv'
data = pd.read_csv(file_path)

# Generate uptime data based on the specified conditions
def generate_uptime(profile):
    if profile == 'KERJA':
        # 70% within 10:00:00 to 17:00:00, 30% outside this range
        if np.random.rand() < 0.7:
            hour = np.random.randint(10, 18)
        else:
            hour = np.random.choice(list(range(0, 10)) + list(range(18, 24)))
    else:
        # 60% within 20:00:00 to 23:00:00, 40% outside this range
        if np.random.rand() < 0.6:
            hour = np.random.randint(20, 24)
        else:
            hour = np.random.choice(list(range(0, 20)))
    
    minute = np.random.randint(0, 60)
    second = np.random.randint(0, 60)
    return f"{hour:02}:{minute:02}:{second:02}"

# Add uptime column
data['uptime'] = data['profile'].apply(generate_uptime)

import ace_tools as tools; 
tools.display_dataframe_to_user(name="Updated Data with Uptime", dataframe=data)

# Save the updated data to a new CSV file
output_path = '/mnt/data/updated_fixedmock.csv'
data.to_csv(output_path, index=False)

output_path